version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      # npm run build시 환경 변수 참조가 안되어 args로 전달하고, Dockerfile에서 변수로 사용한다.
      args:
        - REACT_APP_NAME=Run-Us
        - REACT_APP_TITLE=Run-Us
      ports:
        - "3002:80"